// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNdb1JahIix4XBCYlRFXXePAR20_VsLFo',
    appId: '1:791106535:web:66cc579b0180b71f88e342',
    messagingSenderId: '791106535',
    projectId: 'docstax-fdbms',
    authDomain: 'docstax-fdbms.firebaseapp.com',
    storageBucket: 'docstax-fdbms.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNdb1JahIix4XBCYlRFXXePAR20_VsLFo',
    appId: '1:791106535:android:1519f7d9e0f7c4ee88e342',
    messagingSenderId: '791106535',
    projectId: 'docstax-fdbms',
    storageBucket: 'docstax-fdbms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNdb1JahIix4XBCYlRFXXePAR20_VsLFo',
    appId: '1:791106535:ios:3dd80406e4bb2ff888e342',
    messagingSenderId: '791106535',
    projectId: 'docstax-fdbms',
    storageBucket: 'docstax-fdbms.appspot.com',
    iosBundleId: 'com.shiniemoon.docstax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNdb1JahIix4XBCYlRFXXePAR20_VsLFo',
    appId: '1:791106535:ios:12eca9cd63da7b0a88e342',
    messagingSenderId: '791106535',
    projectId: 'docstax-fdbms',
    storageBucket: 'docstax-fdbms.appspot.com',
    iosBundleId: 'com.shiniemoon.docstax.RunnerTests',
  );
}
